spring:
  aop:
    proxy-target-class: false
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  flyway:
    enabled: true
  profiles:
# Format:
#    osm:
#      api:
#        url: "https://overpass-api.de/api/interpreter"
#    osrm:
#      api:
#        url: "https://api.jawg.io"
#        token: "***"
#        route-uri: "/routing/route/v1/walk"
#        elevations-uri: "/elevations"
    include: 'api-clients'

server:
  port: 8080

springdoc:
  swagger-ui:
    path: "/swagger-ui"

rest:
  api:
    prefix: /api
    version: /v1

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc: DEBUG
    reactor.netty.http.client: DEBUG