spring:
  aop:
    proxy-target-class: false
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  flyway:
    enabled: true
  profiles:
    include: 'api-clients'

server:
  port: 8080

springdoc:
  swagger-ui:
    path: "/swagger-ui"

rest:
  api:
    prefix: /api
    version: /v1

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc: DEBUG
    reactor.netty.http.client: DEBUG